/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverRouteImport } from './routes/over'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductenIndexRouteImport } from './routes/producten.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as ProductenSlugRouteImport } from './routes/producten.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'

const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductenIndexRoute = ProductenIndexRouteImport.update({
  id: '/producten/',
  path: '/producten/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductenSlugRoute = ProductenSlugRouteImport.update({
  id: '/producten/$slug',
  path: '/producten/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/offerte': typeof OfferteRoute
  '/over': typeof OverRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/producten/$slug': typeof ProductenSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/producten/': typeof ProductenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/offerte': typeof OfferteRoute
  '/over': typeof OverRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/producten/$slug': typeof ProductenSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/producten': typeof ProductenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/offerte': typeof OfferteRoute
  '/over': typeof OverRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/producten/$slug': typeof ProductenSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/producten/': typeof ProductenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diensten'
    | '/offerte'
    | '/over'
    | '/portfolio/$slug'
    | '/producten/$slug'
    | '/portfolio/'
    | '/producten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diensten'
    | '/offerte'
    | '/over'
    | '/portfolio/$slug'
    | '/producten/$slug'
    | '/portfolio'
    | '/producten'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diensten'
    | '/offerte'
    | '/over'
    | '/portfolio/$slug'
    | '/producten/$slug'
    | '/portfolio/'
    | '/producten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  OfferteRoute: typeof OfferteRoute
  OverRoute: typeof OverRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ProductenSlugRoute: typeof ProductenSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ProductenIndexRoute: typeof ProductenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producten/': {
      id: '/producten/'
      path: '/producten'
      fullPath: '/producten/'
      preLoaderRoute: typeof ProductenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producten/$slug': {
      id: '/producten/$slug'
      path: '/producten/$slug'
      fullPath: '/producten/$slug'
      preLoaderRoute: typeof ProductenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  OfferteRoute: OfferteRoute,
  OverRoute: OverRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ProductenSlugRoute: ProductenSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ProductenIndexRoute: ProductenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
